apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/launch-stage: BETA
  labels:
    cloud.googleapis.com/location: europe-west1
  name: glcoudmaps-sidecars-test
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
        autoscaling.knative.dev/minScale: '0'
        run.googleapis.com/container-dependencies: '{"nginx": ["frontend"], "frontend":["backend"]}'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 40
      serviceAccountName: gcloudmaps-cloudrun-umsa@gcloudmaps.iam.gserviceaccount.com
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 8080
          name: http1
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
        volumeMounts:
        - mountPath: /etc/nginx/
          name: nginx_config
          readOnly: true
      - image: europe-west1-docker.pkg.dev/gcloudmaps/gcloudmaps/frontend:sidecars5
        name: frontend
        env:
        - name: PORT
          value: '3000'
      - image: europe-west1-docker.pkg.dev/gcloudmaps/gcloudmaps/backend:sidecars
        name: backend
        env:
        - name: PORT
          value: '3001'
      volumes:
      - name: nginx_config
        csi:
         driver: gcsfuse.run.googleapis.com
         volumeAttributes:
          bucketName: gcloudmaps-cloudrun-nginx-conf
