on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
  
jobs:
  runscript:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repository
        uses: actions/checkout@v2.3.4
      - name: Check validity of links
        run:  |
          links=$(jq -r '.nodes[].data.link' "application/backend/data/bigquery.json")
          filtered_links=()

          for link in $(echo "${links[@]}"); do
              if [[ "$link" == https://* ]]; then
                  filtered_links+=("$link")
              fi
          done

          for link in "${filtered_links[@]}"; do
              http_status=$(curl -s -o /dev/null -w "%{http_code}" $link)
              echo "$link"
              echo "$http_status"
          done
