on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
  
jobs:
  runscript:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Test a shell
        run:  echo "hello world"
